import Head from "next/head";
import { Inter } from "next/font/google";
import Table from "@/components/table";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="row stats">
        <div className="col-2">
          <div className="card">
            <div className="card-body text-center text-success">
              <h5 className="card-title">Approved</h5>
              <p className="card-text">10</p>
            </div>
          </div>
        </div>
        <div className="col-2">
          <div className="card">
            <div className="card-body text-center text-danger">
              <h5 className="card-title">Declined</h5>
              <p className="card-text">4</p>
            </div>
          </div>
        </div>
        <div className="col-2">
          <div className="card">
            <div className="card-body text-center text-warning">
              <h5 className="card-title">Pending</h5>
              <p className="card-text">12</p>
            </div>
          </div>
        </div>
      </div>
      <div className="row">
        <div className="col-12">
          <Table />
        </div>
      </div>
    </>
  );
}
